### ISSUE TITLE
About the previous checkpoint on cat2dog

### ISSUE THREAD

**Issue by Star-Stone** [alpc91/NICE-GAN-pytorch#19]
Thank you for your great work.
I have downloaded your previous checkpoint on cat2dog from google drive. The `cat2dog_params_latest.pt` is put into the folder `results`. I run code on the google colab. I run main.py by `python3 main.py --dataset cat2dog --resume True  --light True`. The error occurs.
```
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    main()
  File "main.py", line 77, in main
    gan.train()
  File "/content/gdrive/My Drive/GAN/NICE-GAN-pytorch/NICE.py", line 155, in train
    self.gen2B.load_state_dict(params['gen2B'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "total_ops", "total_params", "UpBlock1_1.total_ops", "UpBlock1_1.total_params", "UpBlock1_1.pad1.total_ops", "UpBlock1_1.pad1.total_params", "UpBlock1_1.norm1.total_ops", "UpBlock1_1.norm1.total_params", "UpBlock1_1.pad2.total_ops", "UpBlock1_1.pad2.total_params", "UpBlock1_1.norm2.total_ops", "UpBlock1_1.norm2.total_params", "UpBlock1_2.total_ops", "UpBlock1_2.total_params", "UpBlock1_2.pad1.total_ops", "UpBlock1_2.pad1.total_params", "UpBlock1_2.norm1.total_ops", "UpBlock1_2.norm1.total_params", "UpBlock1_2.pad2.total_ops", "UpBlock1_2.pad2.total_params", "UpBlock1_2.norm2.total_ops", "UpBlock1_2.norm2.total_params", "UpBlock1_3.total_ops", "UpBlock1_3.total_params", "UpBlock1_3.pad1.total_ops", "UpBlock1_3.pad1.total_params", "UpBlock1_3.norm1.total_ops", "UpBlock1_3.norm1.total_params", "UpBlock1_3.pad2.total_ops", "UpBlock1_3.pad2.total_params", "UpBlock1_3.norm2.total_ops", "UpBlock1_3.norm2.total_params", "UpBlock1_4.total_ops", "UpBlock1_4.total_params", "UpBlock1_4.pad1.total_ops", "UpBlock1_4.pad1.total_params", "UpBlock1_4.norm1.total_ops", "UpBlock1_4.norm1.total_params", "UpBlock1_4.pad2.total_ops", "UpBlock1_4.pad2.total_params", "UpBlock1_4.norm2.total_ops", "UpBlock1_4.norm2.total_params", "UpBlock1_5.total_ops", "UpBlock1_5.total_params", "UpBlock1_5.pad1.total_ops", "UpBlock1_5.pad1.total_params", "UpBlock1_5.norm1.total_ops", "UpBlock1_5.norm1.total_params", "UpBlock1_5.pad2.total_ops", "UpBlock1_5.pad2.total_params", "UpBlock1_5.norm2.total_ops", "UpBlock1_5.norm2.total_params", "UpBlock1_6.total_ops", "UpBlock1_6.total_params", "UpBlock1_6.pad1.total_ops", "UpBlock1_6.pad1.total_params", "UpBlock1_6.norm1.total_ops", "UpBlock1_6.norm1.total_params", "UpBlock1_6.pad2.total_ops", "UpBlock1_6.pad2.total_params", "UpBlock1_6.norm2.total_ops", "UpBlock1_6.norm2.total_params", "FC.total_ops", "FC.total_params", "UpBlock0.total_ops", "UpBlock0.total_params", "UpBlock0.0.total_ops", "UpBlock0.0.total_params", "UpBlock0.2.total_ops", "UpBlock0.2.total_params", "UpBlock2.total_ops", "UpBlock2.total_params", "UpBlock2.0.total_ops", "UpBlock2.0.total_params", "UpBlock2.2.total_ops", "UpBlock2.2.total_params", "UpBlock2.5.total_ops", "UpBlock2.5.total_params", "UpBlock2.6.total_ops", "UpBlock2.6.total_params", "UpBlock2.8.total_ops", "UpBlock2.8.total_params", "UpBlock2.10.total_ops", "UpBlock2.10.total_params", "UpBlock2.13.total_ops", "UpBlock2.13.total_params", "UpBlock2.14.total_ops", "UpBlock2.14.total_params", "UpBlock2.16.total_ops", "UpBlock2.16.total_params", "UpBlock2.18.total_ops", "UpBlock2.18.total_params". 
```

Could you tell me what's wrong?

**Comment by Star-Stone** [comment]
And I also use previous checkpoint for testing and **the same error occurs**.
I run the code:`python main.py --dataset cat2dog --phase test  --light True`
The error is as follows:
```python
number of epochs must be larger than or equal to one

##### Information #####
# light :  True
# dataset :  cat2dog
# batch_size :  1
# iteration per epoch :  300000
# the size of image :  256
# the size of image channel :  3
# base channel number per layer :  64

##### Generator #####
# residual blocks :  6

##### Discriminator #####
# discriminator layers :  7

##### Weight #####
# adv_weight :  1
# cycle_weight :  10
# recon_weight :  10
-----------------------------------------------
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_relu() for <class 'torch.nn.modules.activation.LeakyReLU'>.
[WARN] Cannot find rule for <class 'torch.nn.modules.padding.ReflectionPad2d'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.Discriminator'>. Treat it as zero Macs and zero Params.
[Network disA] Total number of parameters:  93.749M
[Network disA] Total number of FLOPs:  12.013G
-----------------------------------------------
[INFO] Register zero_ops() for <class 'torch.nn.modules.activation.ReLU'>.
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class 'torch.nn.modules.padding.ReflectionPad2d'>. Treat it as zero Macs and zero Params.
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[WARN] Cannot find rule for <class 'networks.adaILN'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.ResnetAdaILNBlock'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.ILN'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.pixelshuffle.PixelShuffle'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.activation.Tanh'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.ResnetGenerator'>. Treat it as zero Macs and zero Params.
[Network gen2B] Total number of parameters:  16.192M
[Network gen2B] Total number of FLOPs:  67.552G
-----------------------------------------------
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    main()
  File "main.py", line 81, in main
    gan.test()
  File "/content/gdrive/My Drive/GAN/NICE-GAN-pytorch/NICE.py", line 442, in test
    self.load()
  File "/content/gdrive/My Drive/GAN/NICE-GAN-pytorch/NICE.py", line 433, in load
    self.gen2B.load_state_dict(params['gen2B'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "total_ops", "total_params", "UpBlock1_1.total_ops", "UpBlock1_1.total_params", "UpBlock1_1.pad1.total_ops", "UpBlock1_1.pad1.total_params", "UpBlock1_1.norm1.total_ops", "UpBlock1_1.norm1.total_params", "UpBlock1_1.pad2.total_ops", "UpBlock1_1.pad2.total_params", "UpBlock1_1.norm2.total_ops", "UpBlock1_1.norm2.total_params", "UpBlock1_2.total_ops", "UpBlock1_2.total_params", "UpBlock1_2.pad1.total_ops", "UpBlock1_2.pad1.total_params", "UpBlock1_2.norm1.total_ops", "UpBlock1_2.norm1.total_params", "UpBlock1_2.pad2.total_ops", "UpBlock1_2.pad2.total_params", "UpBlock1_2.norm2.total_ops", "UpBlock1_2.norm2.total_params", "UpBlock1_3.total_ops", "UpBlock1_3.total_params", "UpBlock1_3.pad1.total_ops", "UpBlock1_3.pad1.total_params", "UpBlock1_3.norm1.total_ops", "UpBlock1_3.norm1.total_params", "UpBlock1_3.pad2.total_ops", "UpBlock1_3.pad2.total_params", "UpBlock1_3.norm2.total_ops", "UpBlock1_3.norm2.total_params", "UpBlock1_4.total_ops", "UpBlock1_4.total_params", "UpBlock1_4.pad1.total_ops", "UpBlock1_4.pad1.total_params", "UpBlock1_4.norm1.total_ops", "UpBlock1_4.norm1.total_params", "UpBlock1_4.pad2.total_ops", "UpBlock1_4.pad2.total_params", "UpBlock1_4.norm2.total_ops", "UpBlock1_4.norm2.total_params", "UpBlock1_5.total_ops", "UpBlock1_5.total_params", "UpBlock1_5.pad1.total_ops", "UpBlock1_5.pad1.total_params", "UpBlock1_5.norm1.total_ops", "UpBlock1_5.norm1.total_params", "UpBlock1_5.pad2.total_ops", "UpBlock1_5.pad2.total_params", "UpBlock1_5.norm2.total_ops", "UpBlock1_5.norm2.total_params", "UpBlock1_6.total_ops", "UpBlock1_6.total_params", "UpBlock1_6.pad1.total_ops", "UpBlock1_6.pad1.total_params", "UpBlock1_6.norm1.total_ops", "UpBlock1_6.norm1.total_params", "UpBlock1_6.pad2.total_ops", "UpBlock1_6.pad2.total_params", "UpBlock1_6.norm2.total_ops", "UpBlock1_6.norm2.total_params", "FC.total_ops", "FC.total_params", "UpBlock0.total_ops", "UpBlock0.total_params", "UpBlock0.0.total_ops", "UpBlock0.0.total_params", "UpBlock0.2.total_ops", "UpBlock0.2.total_params", "UpBlock2.total_ops", "UpBlock2.total_params", "UpBlock2.0.total_ops", "UpBlock2.0.total_params", "UpBlock2.2.total_ops", "UpBlock2.2.total_params", "UpBlock2.5.total_ops", "UpBlock2.5.total_params", "UpBlock2.6.total_ops", "UpBlock2.6.total_params", "UpBlock2.8.total_ops", "UpBlock2.8.total_params", "UpBlock2.10.total_ops", "UpBlock2.10.total_params", "UpBlock2.13.total_ops", "UpBlock2.13.total_params", "UpBlock2.14.total_ops", "UpBlock2.14.total_params", "UpBlock2.16.total_ops", "UpBlock2.16.total_params", "UpBlock2.18.total_ops", "UpBlock2.18.total_params". 
```
Actually I also train 100000 iterations  on NVIDIA GeForce RTX 2080 and it takes 17.5 hours indeed. And I use generated checkpoint for testing. I run `python3 main.py --dataset cat2dog --phase test  --light True` and **it works**. Message is as follows:
```python
number of epochs must be larger than or equal to one

##### Information #####
# light :  True
# dataset :  cat2dog
# batch_size :  1
# iteration per epoch :  300000
# the size of image :  256
# the size of image channel :  3
# base channel number per layer :  64

##### Generator #####
# residual blocks :  6

##### Discriminator #####
# discriminator layers :  7

##### Weight #####
# adv_weight :  1
# cycle_weight :  10
# recon_weight :  10
-----------------------------------------------
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_relu() for <class 'torch.nn.modules.activation.LeakyReLU'>.
[WARN] Cannot find rule for <class 'torch.nn.modules.padding.ReflectionPad2d'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.Discriminator'>. Treat it as zero Macs and zero Params.
[Network disA] Total number of parameters:  93.749M
[Network disA] Total number of FLOPs:  12.013G
-----------------------------------------------
[INFO] Register zero_ops() for <class 'torch.nn.modules.activation.ReLU'>.
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class 'torch.nn.modules.padding.ReflectionPad2d'>. Treat it as zero Macs and zero Params.
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[WARN] Cannot find rule for <class 'networks.adaILN'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.ResnetAdaILNBlock'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.ILN'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.pixelshuffle.PixelShuffle'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'torch.nn.modules.activation.Tanh'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'networks.ResnetGenerator'>. Treat it as zero Macs and zero Params.
[Network gen2B] Total number of parameters:  16.192M
[Network gen2B] Total number of FLOPs:  67.552G
-----------------------------------------------
100000
dataset/cat2dog/testA/103.jpg
dataset/cat2dog/testA/104.jpg
dataset/cat2dog/testA/13.jpg
dataset/cat2dog/testA/136.jpg
dataset/cat2dog/testA/138.jpg
dataset/cat2dog/testA/14.jpg
dataset/cat2dog/testA/143.jpg
dataset/cat2dog/testA/144.jpg
dataset/cat2dog/testA/171.jpg
dataset/cat2dog/testA/176.jpg
dataset/cat2dog/testA/178.jpg
dataset/cat2dog/testA/192.jpg
dataset/cat2dog/testA/195.jpg
dataset/cat2dog/testA/21.jpg
dataset/cat2dog/testA/213.jpg
dataset/cat2dog/testA/214.jpg
dataset/cat2dog/testA/221.jpg
dataset/cat2dog/testA/228.jpg
dataset/cat2dog/testA/253.jpg
dataset/cat2dog/testA/254.jpg
dataset/cat2dog/testA/26.jpg
dataset/cat2dog/testA/261.jpg
dataset/cat2dog/testA/266.jpg
dataset/cat2dog/testA/268.jpg
dataset/cat2dog/testA/28.jpg
dataset/cat2dog/testA/282.jpg
dataset/cat2dog/testA/285.jpg
dataset/cat2dog/testA/302.jpg
dataset/cat2dog/testA/305.jpg
dataset/cat2dog/testA/330.jpg
dataset/cat2dog/testA/337.jpg
dataset/cat2dog/testA/339.jpg
dataset/cat2dog/testA/342.jpg
dataset/cat2dog/testA/345.jpg
dataset/cat2dog/testA/370.jpg
dataset/cat2dog/testA/377.jpg
dataset/cat2dog/testA/379.jpg
dataset/cat2dog/testA/393.jpg
dataset/cat2dog/testA/394.jpg
dataset/cat2dog/testA/401.jpg
dataset/cat2dog/testA/406.jpg
dataset/cat2dog/testA/433.jpg
dataset/cat2dog/testA/434.jpg
dataset/cat2dog/testA/441.jpg
dataset/cat2dog/testA/446.jpg
dataset/cat2dog/testA/448.jpg
dataset/cat2dog/testA/473.jpg
dataset/cat2dog/testA/474.jpg
dataset/cat2dog/testA/490.jpg
dataset/cat2dog/testA/497.jpg
dataset/cat2dog/testA/499.jpg
dataset/cat2dog/testA/510.jpg
dataset/cat2dog/testA/517.jpg
dataset/cat2dog/testA/519.jpg
dataset/cat2dog/testA/522.jpg
dataset/cat2dog/testA/525.jpg
dataset/cat2dog/testA/53.jpg
dataset/cat2dog/testA/54.jpg
dataset/cat2dog/testA/557.jpg
dataset/cat2dog/testA/559.jpg
dataset/cat2dog/testA/562.jpg
dataset/cat2dog/testA/565.jpg
dataset/cat2dog/testA/586.jpg
dataset/cat2dog/testA/588.jpg
dataset/cat2dog/testA/600.jpg
dataset/cat2dog/testA/607.jpg
dataset/cat2dog/testA/609.jpg
dataset/cat2dog/testA/61.jpg
dataset/cat2dog/testA/632.jpg
dataset/cat2dog/testA/635.jpg
dataset/cat2dog/testA/640.jpg
dataset/cat2dog/testA/649.jpg
dataset/cat2dog/testA/66.jpg
dataset/cat2dog/testA/672.jpg
dataset/cat2dog/testA/675.jpg
dataset/cat2dog/testA/68.jpg
dataset/cat2dog/testA/691.jpg
dataset/cat2dog/testA/698.jpg
dataset/cat2dog/testA/711.jpg
dataset/cat2dog/testA/716.jpg
dataset/cat2dog/testA/718.jpg
dataset/cat2dog/testA/723.jpg
dataset/cat2dog/testA/724.jpg
dataset/cat2dog/testA/751.jpg
dataset/cat2dog/testA/756.jpg
dataset/cat2dog/testA/758.jpg
dataset/cat2dog/testA/763.jpg
dataset/cat2dog/testA/764.jpg
dataset/cat2dog/testA/780.jpg
dataset/cat2dog/testA/787.jpg
dataset/cat2dog/testA/789.jpg
dataset/cat2dog/testA/801.jpg
dataset/cat2dog/testA/808.jpg
dataset/cat2dog/testA/82.jpg
dataset/cat2dog/testA/833.jpg
dataset/cat2dog/testA/834.jpg
dataset/cat2dog/testA/841.jpg
dataset/cat2dog/testA/846.jpg
dataset/cat2dog/testA/848.jpg
dataset/cat2dog/testA/85.jpg
dataset/cat2dog/testB/1092.jpg
dataset/cat2dog/testB/1095.jpg
dataset/cat2dog/testB/1112.jpg
dataset/cat2dog/testB/1115.jpg
dataset/cat2dog/testB/112.jpg
dataset/cat2dog/testB/1127.jpg
dataset/cat2dog/testB/115.jpg
dataset/cat2dog/testB/1160.jpg
dataset/cat2dog/testB/1167.jpg
dataset/cat2dog/testB/1169.jpg
dataset/cat2dog/testB/120.jpg
dataset/cat2dog/testB/1202.jpg
dataset/cat2dog/testB/1205.jpg
dataset/cat2dog/testB/1230.jpg
dataset/cat2dog/testB/1270.jpg
dataset/cat2dog/testB/1277.jpg
dataset/cat2dog/testB/1279.jpg
dataset/cat2dog/testB/1314.jpg
dataset/cat2dog/testB/1321.jpg
dataset/cat2dog/testB/1326.jpg
dataset/cat2dog/testB/1328.jpg
dataset/cat2dog/testB/1353.jpg
dataset/cat2dog/testB/1354.jpg
dataset/cat2dog/testB/1368.jpg
dataset/cat2dog/testB/1382.jpg
dataset/cat2dog/testB/1385.jpg
dataset/cat2dog/testB/14.jpg
dataset/cat2dog/testB/1422.jpg
dataset/cat2dog/testB/1425.jpg
dataset/cat2dog/testB/1450.jpg
dataset/cat2dog/testB/1457.jpg
dataset/cat2dog/testB/1459.jpg
dataset/cat2dog/testB/1481.jpg
dataset/cat2dog/testB/1486.jpg
dataset/cat2dog/testB/1488.jpg
dataset/cat2dog/testB/1501.jpg
dataset/cat2dog/testB/1506.jpg
dataset/cat2dog/testB/1508.jpg
dataset/cat2dog/testB/1546.jpg
dataset/cat2dog/testB/1573.jpg
dataset/cat2dog/testB/1574.jpg
dataset/cat2dog/testB/1597.jpg
dataset/cat2dog/testB/160.jpg
dataset/cat2dog/testB/1611.jpg
dataset/cat2dog/testB/1616.jpg
dataset/cat2dog/testB/1618.jpg
dataset/cat2dog/testB/1651.jpg
dataset/cat2dog/testB/1663.jpg
dataset/cat2dog/testB/1664.jpg
dataset/cat2dog/testB/167.jpg
dataset/cat2dog/testB/1680.jpg
dataset/cat2dog/testB/169.jpg
dataset/cat2dog/testB/1709.jpg
dataset/cat2dog/testB/202.jpg
dataset/cat2dog/testB/205.jpg
dataset/cat2dog/testB/21.jpg
dataset/cat2dog/testB/237.jpg
dataset/cat2dog/testB/26.jpg
dataset/cat2dog/testB/270.jpg
dataset/cat2dog/testB/277.jpg
dataset/cat2dog/testB/279.jpg
dataset/cat2dog/testB/28.jpg
dataset/cat2dog/testB/313.jpg
dataset/cat2dog/testB/321.jpg
dataset/cat2dog/testB/326.jpg
dataset/cat2dog/testB/328.jpg
dataset/cat2dog/testB/353.jpg
dataset/cat2dog/testB/354.jpg
dataset/cat2dog/testB/382.jpg
dataset/cat2dog/testB/385.jpg
dataset/cat2dog/testB/419.jpg
dataset/cat2dog/testB/422.jpg
dataset/cat2dog/testB/425.jpg
dataset/cat2dog/testB/450.jpg
dataset/cat2dog/testB/457.jpg
dataset/cat2dog/testB/459.jpg
dataset/cat2dog/testB/465.jpg
dataset/cat2dog/testB/481.jpg
dataset/cat2dog/testB/486.jpg
dataset/cat2dog/testB/488.jpg
dataset/cat2dog/testB/5.jpg
dataset/cat2dog/testB/501.jpg
dataset/cat2dog/testB/506.jpg
dataset/cat2dog/testB/508.jpg
dataset/cat2dog/testB/53.jpg
dataset/cat2dog/testB/54.jpg
dataset/cat2dog/testB/541.jpg
dataset/cat2dog/testB/573.jpg
dataset/cat2dog/testB/574.jpg
dataset/cat2dog/testB/590.jpg
dataset/cat2dog/testB/611.jpg
dataset/cat2dog/testB/616.jpg
dataset/cat2dog/testB/618.jpg
dataset/cat2dog/testB/656.jpg
dataset/cat2dog/testB/663.jpg
dataset/cat2dog/testB/664.jpg
dataset/cat2dog/testB/68.jpg
dataset/cat2dog/testB/687.jpg
dataset/cat2dog/testB/82.jpg
dataset/cat2dog/testB/85.jpg
 [*] Test finished!
```
I guess whether some ResnetGenerator information was not saved in the previous checkpoint.

**Comment by BruceYu-Bit** [comment]
如何使用多卡训练

**Comment by Star-Stone** [comment]
Sorry, my pytorch version is 1.6.0 . I can use it for training and can not use it for test. When I choose pytorch 1.1.0, it can be used for  test.
